# hooks.py - хуки для PyInstaller
import sys
import os

def get_hidden_imports():
    """Возвращает список скрытых импортов для PyInstaller"""
    hidden_imports = [
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'uvicorn.lifespan.on',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.logging',
        'fastapi.openapi.docs',
        'fastapi.openapi.utils',
        'fastapi.responses',
        'fastapi.routing',
        'fastapi.dependencies',
        'fastapi.security',
        'fastapi.middleware',
        'fastapi.encoders',
        'fastapi.datastructures',
        'fastapi.params',
        'fastapi.background',
        'fastapi.concurrency',
        'fastapi.exception_handlers',
        'fastapi.exceptions',
        'fastapi.utils',
        'fastapi.types',
        'starlette.routing',
        'starlette.responses',
        'starlette.requests',
        'starlette.datastructures',
        'starlette.convertors',
        'starlette.middleware',
        'starlette.middleware.base',
        'starlette.middleware.cors',
        'starlette.middleware.gzip',
        'starlette.middleware.trustedhost',
        'starlette.middleware.httpsredirect',
        'starlette.middleware.sessions',
        'starlette.middleware.authentication',
        'starlette.middleware.wsgi',
        'starlette.staticfiles',
        'starlette.templating',
        'starlette.testclient',
        'starlette.websockets',
        'starlette.background',
        'starlette.concurrency',
        'starlette.endpoints',
        'starlette.exceptions',
        'starlette.status',
        'starlette.types',
        'starlette.authentication',
        'starlette.applications',
        'starlette.schemas',
        'starlette.graphql',
        'starlette.middleware.errors',
        'starlette.middleware.httpsredirect',
        'starlette.middleware.trustedhost',
        'starlette.middleware.sessions',
        'starlette.middleware.authentication',
        'starlette.middleware.wsgi'
    ]
    return hidden_imports